### ISSUE TITLE
how to properly define graphQL types in `.js` files

### ISSUE THREAD

**Issue by Rulsky** [kumarharsh/graphql-for-vscode#108]
I use apollo's [graphql-tools](https://github.com/apollographql/graphql-tools) for my my graphql backend and types are defined in `.js` files.

For example:
```javascript
// Person.gql.js
export default `
type Person {
  id: ID!,
  first: String!,
  last: String!,
}
`
```

but I get syntax errors from your tool.
So how to properly define types to be compatible with your tool?

**Comment by Mayank1791989** [comment]
@Rulsky Currently we do not support schema in js files.  I have created an  [issue](https://github.com/Mayank1791989/gql/issues/144) in @playlyfe/gql for this.

> So how to properly define types to be compatible with your tool?

For now you have to generate ```schema.graphql``` file.
