### ISSUE TITLE
gqlModule.GQL is not a constructor

### ISSUE THREAD

**Issue by majodev** [kumarharsh/graphql-for-vscode#12]
Hi!

Looks like the latest [@playlyfe/gql@v2.0.0](https://github.com/Mayank1791989/gql/releases/tag/v2.0.0) release breaks this extension [here](https://github.com/kumarharsh/graphql-for-vscode/blob/48a4975d213802b0c9e389ba01e3e6c6ba00768e/src/server/server.ts#L80).

Editor Output:
```
[Info  - 11:46:06] NODE_PATH value is: /Users/USER/PROJECT
[Info  - 11:46:06] Module '@playlyfe/gql' loaded from: /Users/USER/PROJECT/node_modules/@playlyfe/gql/lib/index.js
[Error - 11:46:06] Server initialization failed.
  Message: Request initialize failed with message: gqlModule.GQL is not a constructor
  Code: -32603 
```

**Comment by kumarharsh** [comment]
@majodev yes, v2 of @playlyfe/gql has some breaking changes. I'm working on getting a release with the latest version in place soon. Till that time, please use the v1 releases of @playlyfe/gql.

**Comment by kumarharsh** [comment]
I've released the new version, which fixes this issue. Kindly upgrade the `@playlyfe/gql` package to the x2.x branch.

**Comment by majodev** [comment]
Just checked, it's really now awesome with query code completion. Keep up the good work!

**Comment by kumarharsh** [comment]
Thank you @majodev!
