### ISSUE TITLE
Error in VSCode

### ISSUE THREAD

**Issue by idibidiart** [kumarharsh/graphql-for-vscode#13]
[Error - 6:14:30 AM] Server initialization failed.
  Message: Request initialize failed with message: Couldn't find module '@playlyfe/gql' in path

**Comment by kumarharsh** [comment]
@idibidiart please see the Setup instructions in the readme. https://github.com/kumarharsh/graphql-for-vscode#setting-it-up

**Comment by idibidiart** [comment]
@kumarharsh the link to install @playlyfe/gql  is broken .... 

https://github.com/kumarharsh/graphql-for-vscode/blob/master/npmjs.org/package/@playlyfe/gql

**Comment by kumarharsh** [comment]
Thanks for pointing out the error. I'll get it corrected soon 😄
