### ISSUE TITLE
Syntaxes fails when use `#{ … }` in heredoc in Ruby

### ISSUE THREAD

**Issue by jerrywdlee** [kumarharsh/graphql-for-vscode#142]
When use `<<GRAPHQL` heredoc  in ruby, it got an grammar error when I tried to embed variables inside them.

![dataset_type_spec_rb_—_caesaris](https://user-images.githubusercontent.com/10390079/60707578-0b255080-9f47-11e9-89a7-e0a70647e86a.png)

Should be

![dataset_type_spec_rb_—_caesaris](https://user-images.githubusercontent.com/10390079/60707628-25f7c500-9f47-11e9-827c-d5cd010d2cf4.png)

**Comment by kumarharsh** [comment]
Closed in 34bb681, released in 1.14.1
