### ISSUE TITLE
Relay specific features

### ISSUE THREAD

**Issue by alloy** [kumarharsh/graphql-for-vscode#15]
Hi,

For [this tool to generate TypeScript interfaces for Relay queries](https://github.com/alloy/relay2ts) I had started on [a VSCode extension](https://github.com/alloy/vscode-relay) that basically just wraps that tool.

Later on I found your extension and I’m wondering how you see the overlap in these things and if you think we could/should merge this work of mine into your extension instead, or if it’s too Relay/TypeScript specific?

**Comment by kumarharsh** [comment]
Hey, great idea, let me have a look. Haven't worked on TS+Relay projects yet, so I don't completely understand the need. Let me take a look around, and I'll come back with my thoughts in a little while.

**Comment by alloy** [comment]
I will add that since then I’ve learned that Relay 2 is going to be outputting Flow typings for the fragments during compilation and they’ve told me that that would be the right place for me to generate TypeScript typings as well. But seeing as Relay 2 is not available in any form yet, we’ll have to wait and see how well this integrates with an open editor session and if there’s still a need for an editor specific (vscode) extension.

**Comment by kumarharsh** [comment]
@alloy as per your previous comment, I'm going to close this issue for now.
