### ISSUE TITLE
Greenkeeper badge image is not showing in readme.md

### ISSUE THREAD

**Issue by syeutyu** [kumarharsh/graphql-for-vscode#150]
<img width="906" alt="스크린샷 2019-07-12 오후 2 38 31" src="https://user-images.githubusercontent.com/25384956/61104922-087cab00-a4b3-11e9-9f59-2c754ae47723.png">

Greenkeeper badge image url is not found so click that image redirect greenkeeper.io url

**Comment by kumarharsh** [comment]
Yeah, I've removed greenkeeper - will remove the badge. Thanks for reporting.
