### ISSUE TITLE
Bundle @playlyfe/gql

### ISSUE THREAD

**Issue by felixfbecker** [kumarharsh/graphql-for-vscode#16]
Why do I have to install it manually, and even a specific version?

**Comment by kumarharsh** [comment]
@playlyfe/gql does more than just provide autocomplete support. You can use the library to build your schema files into json, lint them in pre-commit hooks, and even integrate the build process with webpack with watch (this is in-works). I've thought about bundling it, but the benefits of using it beyond just the plugin have kept me from doing it.

**Comment by felixfbecker** [comment]
That's nice, but in projects where it is not used this is annoying - is there any disadvantage to bundling it? It clearly is a dependency of the language server

**Comment by kumarharsh** [comment]
I understand your position @felixfbecker. But you have to see that the gql library **is** the heart of a language server, and the code in this vscode extension is just a thin wrapper over it. The gql library can form a common base for language servers for other editors such as Sublime Text, Atom, etc too. If all developers in your team are not *in* for vscode, then they can use the editor of their choice and still get the same benefits. As of this moment, there aren't any plugins for other editors, but that might change, and I think it'll be best to keep it separate.

Plus, this is the same approach as taken by the authors of `vscode-eslint` - which requires that you install the eslint package as a dependency for your project. So, right now, I'm not motivated in working on bundling the library. I thank you for your input, and hope the plugin proves useful in your work. 🙂

**Comment by felixfbecker** [comment]
Hm ESLint is a linter though, this is a language service. And the version you use in your project might not even be compatible with the version the extension requires...
FYI in my PHP IntelliSense extension (which is just a small wrapper around the PHP language server) I bundle the language server, I would find it weird if every user had to install it into their workspaces.

But I get your reasoning. Thanks for considering and keep up the great work :)
