### ISSUE TITLE
Confusing configuration in README

### ISSUE THREAD

**Issue by Maxwell2022** [kumarharsh/graphql-for-vscode#162]
I'm trying to configure this plugin for a project that uses Apollo Client. The short story, I cannot make this plugin work for now. The long story:

I'm going through the README step by step and I cannot manage to make it work.
My graphQL server is not running on Apollo Engine, I don't know if this makes a difference or not. Following the README:

> 1. Ensure that you have the @playlyfe/gql library (v2.x) installed and available to this extension. If you've installed the library in a folder other than the workspace root, then add the path to the node_modules directory as a setting:

I do have `@playlyfe/gql` (2.6.1) installed in my project so I guess I don't have to do anything here. However, what is **add the path to the node_modules directory as a setting**? What settings? In which settings file vscode extension settings? 

> 2. Ensure you have watchman installed

This is all good

> 3. Create a .gqlconfig file

Okay, I've done that. It's a bit confusing because my client project doesn't have `.gql` or `.graphql` files. I'm using the `gql` template literal.

> 4. Enable auto-complete

I've tried this, even tho I don't have the field validation working or the syntax highlighting neither.

I cannot see any errors in the logs or maybe I'm not looking at the right place. Anyone can help? I swear that once I have it working I'll create a PR to clarify the setup or maybe the troubleshooting.

**Comment by kumarharsh** [comment]
The `nodePath` setting has to be configured, like shown below. This is the path where the `@playlyfe/gql` node module should be found.

```
"graphqlForVSCode.nodePath": "ui/node_modules",
```

**Comment by Maxwell2022** [comment]
I would think that the default path would be the workspace `node_modules`.

Anyway, I've added the following in my `.vscode/settings.json`:
```
"graphqlForVSCode.nodePath": "./node_modules"
```

I've restarted VS Code. I think the syntax highlighting is working but the autocomplete is not. I don't know where I should put my graphql endpoint in order to fetch the schema and validate my query.

**Comment by kumarharsh** [comment]
I've found a bug in autocomplete in the latest release. Will be pushing a fix shortly

**Comment by kumarharsh** [comment]
Can you update the extension and try again?

**Comment by Maxwell2022** [comment]
Thanks @kumarharsh, I would love to test it. However, I'm still confused about where to set up the endpoint of my schema introspection so that GQL can actually validate my queries / mutations against it.

**Comment by Mayank1791989** [comment]
@Maxwell2022 Looks like your `.gqlconfig` is not configured correctly. Share your config file and graphql output panel logs.

**Comment by Maxwell2022** [comment]
Thanks @Mayank1791989, here is my `.gqlconfig`:

```
{
  schema: {
    files: 'src/*.graphql'
  }
}
```

Why I am confused is because I'm on a mobile application project (using Apollo Client) but I don't have any file with the `.gql` or `.graphql` extension in this project.
I just use the `gql` template literal and I'm wondering how the vscode plugin or `gql` knows where it should look at to get my schema definition. I'm hosting my graphQL API on my own server, I'm not using Apollo Engine.

**Comment by Mayank1791989** [comment]
In `.gqlconfig` there are two sections one for schema (schema key) and one for clients (queries key). For schema you have to point to the files which contains schema definition (SDL) and it's required for plugin to start. Sample schema file looks like this
```graphql
type Query {
  user: User!
}

type User {
  id: ID!
}
``` 
If you are using graphql-js you can use printSchema to generate one.

**Comment by Maxwell2022** [comment]
That's what I thought so I used `graphql-cli` to download the my server schema in my client project.

in my `package.json` I have a script to fetch this schema:
```
"gql:fetch-schema": "graphql get-schema --project prod",
```

Which is reading the `.graphqlconfig.yml` file from my client project, download the schema and save it to the destination:

```
projects:
  prod:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://api.xxxxxx.com/graphql
```

So I have my `schema.graphql` in my `src` folder.
Which match my `.gqlconfig`configuration:

```
{
  schema: {
    files: 'src/*.graphql'
  }
}
```

But still not validate anything in my query, I can try to fetch a field that does not exist in a query and it's not complaining about it.

**Comment by Maxwell2022** [comment]
I can't see the graphqQL output panel in vscode:
![image](https://user-images.githubusercontent.com/670701/62675274-afd4fb00-b9e9-11e9-8789-423ed35451ab.png)

**Comment by Mayank1791989** [comment]
Try running plugin with this schema 
```graphql
type Query {
  user: User
}

type User {
  id: ID!
}
```

**Comment by Maxwell2022** [comment]
Still not validating correctly:

![image](https://user-images.githubusercontent.com/670701/62675784-bf554380-b9eb-11e9-8899-25a0a2fc5253.png)

![image](https://user-images.githubusercontent.com/670701/62675798-ca0fd880-b9eb-11e9-815f-f3cb1ea86a81.png)

![image](https://user-images.githubusercontent.com/670701/62675804-d005b980-b9eb-11e9-8e88-2fb2808249f1.png)

**Comment by Mayank1791989** [comment]
Is plugin showing running. You will see `GQL` icon in status bar.
![Screenshot_2019-08-08_10-13-27](https://user-images.githubusercontent.com/1512953/62675897-82c32100-b9c6-11e9-9e1a-a7aaac70133b.png)

**Comment by Maxwell2022** [comment]
okay, I found the first issue 😬

![image](https://user-images.githubusercontent.com/670701/62676216-625a8d00-b9ed-11e9-9c6d-4b80f552d5b5.png)

Now GQL is starting and I can see GraphQL in the output panel:

```
[2019-08-08T14:59:35.843] [INFO] gql-language-server - running in node v10.11.0 (/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper)
[2019-08-08T14:59:35.849] [INFO] load-gql-service - loading @playlyfe/gql...
[2019-08-08T14:59:36.340] [INFO] load-gql-service - using @playlyfe/gql from path /Users/maxime/Projects/mobile-app/node_modules
[2019-08-08T14:59:36.343] [INFO] gql-language-server - starting gql service...
[Watch established (gqlSchemaFiles)] 
	basePath: /Users/maxime/Projects/mobile-app 
	RelativePath: undefined 
	Files: "src/**/*.graphql"
[Watch established (gqlQueryFiles-0)] 
	basePath: /Users/maxime/Projects/mobile-app 
	RelativePath: undefined 
	Files: "src/**/*.{js,ts,tsx}"
```

It looks like the `GQL` still in sync

![image](https://user-images.githubusercontent.com/670701/62676376-02181b00-b9ee-11e9-9430-7184b6942420.png)

**Comment by Mayank1791989** [comment]
Comment the query section of .gqlconfig and check validation, autocomplete other features working in your schema file.

**Comment by Maxwell2022** [comment]
Okay so now it looks like the `gql-language-server` started 

![image](https://user-images.githubusercontent.com/670701/62676898-a5b5fb00-b9ef-11e9-9791-ead904b52da9.png)

I'm using the same folder structure for the schema just to be sure. However the validation still not work.

.gqlconfig:
```
{
  schema: {
    files: 'schema/**/*.graphql',
  },
}
```

![image](https://user-images.githubusercontent.com/670701/62676943-d39b3f80-b9ef-11e9-89fd-3f1915cb90eb.png)

![image](https://user-images.githubusercontent.com/670701/62676955-dac24d80-b9ef-11e9-9b2a-6d45b503b284.png)

The only thing I can see it the extension that I'm using is `.tsx`

**Comment by Mayank1791989** [comment]
Try hovering over `ID` in schema file or go to definition on `User`.

**Comment by Maxwell2022** [comment]
It looks like this is working:

![image](https://user-images.githubusercontent.com/670701/62677079-56bc9580-b9f0-11e9-986c-4dacec2050f3.png)

I've tried a simple `arc/test.js` and it still not validating:

![image](https://user-images.githubusercontent.com/670701/62677169-b87cff80-b9f0-11e9-9da6-47561d48c5d3.png)

**Comment by Mayank1791989** [comment]
What is your `.gqlconfig` above?

**Comment by Maxwell2022** [comment]
This is my current `./.gqlconfig`
```
{
  schema: {
    files: 'schema/**/*.graphql',
  },
}
```

**Comment by Mayank1791989** [comment]
You need to add query for client files.
```javascript
{
  schema: {
    files: 'schema/**/*.graphql'
  },
  query: {
    files: [
      {
        match: 'src/**/*.tsx',
        parser: [
          'EmbeddedQueryParser',
          { startTag: 'gql`', endTag: '`' }
        ]
      }
    ]
  }
}
```

**Comment by Maxwell2022** [comment]
Now it's working for my `src/test.js`

![image](https://user-images.githubusercontent.com/670701/62677439-a8b1eb00-b9f1-11e9-9b78-264a4efd8bd1.png)

It looks like I can't use regex for the match. As soon as I change the config to match `.tsx` alongside `.js` the GQL plugin hang 

```
match: 'src/**/*.{js,tsx}',
```

**Comment by Mayank1791989** [comment]
Use this instead `match: ['src/**/*.js', 'src/**/*.tsx']`. I thinks watchman is not supporting this `match: 'src/**/*.{js,tsx}'` syntax. Will look into it.

**Comment by Maxwell2022** [comment]
And I think that's it! Thank you so much!

It's working great now. I'll submit a PR by the end of the week to improve the readme.
Thanks again a lot for your time

**Comment by Mayank1791989** [comment]
Also note currently this plugin supports only [graphql-spec oct16](https://graphql.github.io/graphql-spec/October2016/). So make your schema files doesn't use some new syntax (like docString or '&' in implements).

**Comment by Maxwell2022** [comment]
Here is the PR https://github.com/kumarharsh/graphql-for-vscode/pull/171/files
