### ISSUE TITLE
My schema is templated in JS

### ISSUE THREAD

**Issue by idibidiart** [kumarharsh/graphql-for-vscode#18]
`const typeDefinitions = `
enum Category {
  POLITICS
  TECHNOLOGY
  SPORTS
  OTHER
} 
etc ...
`;
export default [typeDefinitions]
`

....

Trying to get GraphQL plugin for VSCode working but the above format doesn't seem to be supported as the example mentions .gql files, not .js

Is the above format supported or not?

**Comment by kumarharsh** [comment]
No, currently we only support .gql files. By the way, may I ask why you're doing it this way? Just curious. If you're compiling the schema, you can use webpack on gql files directly too.

Also, supporting JS schema would require some additional overhead such as involving babel for parsing and compiling the JS, etc, which would increase the startup time.

**Comment by Alexisvt** [comment]
Can you please provide an example of how to do that? Thanks

**Comment by kumarharsh** [comment]
@Alexisvt take a look at this gist: https://gist.github.com/kumarharsh/4a4ee5d8f9c9b8153adad2a7ab21cb71
