### ISSUE TITLE
Type "BigDecimal" not found

### ISSUE THREAD

**Issue by ugputu18** [kumarharsh/graphql-for-vscode#19]
BigDecimal is a valid type for graphql data. We use it with react-relay. Please add support of this type.

**Comment by kumarharsh** [comment]
@ugputu18 BigDecimal is not in the official graphql spec: http://graphql.org/graphql-js/type. You have to define custom scalars for these type of things. Are you using a different implementation of graphql like Java?

**Comment by pungggi** [comment]
I have a similar issue with DateTime.. 
Would be nice to be able to specify those unofficials in a config or so. Is that possible?

**Comment by jhalborg** [comment]
+1 for DateTime. Got my schema from working with graph.cool, as I imagine a lot of other GraphQL beginners are :-) 

@kumarharsh - Is there any way to add these custom scalars at the moment? Sorry if I missed it

**Comment by Mayank1791989** [comment]
@jhalborg you can define all your custom scalars in new graphql file and add that to schema.files in config.

```graphql
scalar DateTime
```
