### ISSUE TITLE
type & input directive syntax highlighting

### ISSUE THREAD

**Issue by xpepermint** [kumarharsh/graphql-for-vscode#21]
The current version of this extension (`v1.1.1`) does not handle type/input related directives.

Example:
```graphql
# example 1
type MyType @mydirective(kind: "fake", value: "foo") { ... }

# example 2
input MyInput
@mydirective(
  kind: "fake",
  value: "foo")
{ ... }
```

**Comment by kumarharsh** [comment]
@xpepermint can you provide with a link where I can learn more about this? From what I see in the official spec, there are only two directives supported for queries, but none for type or input. Ref: http://graphql.org/learn/queries/#directives

**Comment by xpepermint** [comment]
@kumarharsh not all features are documented but have been in use for months. You should check the [graphql-js](https://github.com/graphql/graphql-js) implementation to see that. You can use `parse` method to see the available features.

Example:
```
import { parse } from "graphql";
parse(`
type Query {
   version: String
   # and so on ...
}
`);
```

**Comment by xpepermint** [comment]
Also: https://github.com/graphql/graphql-js/issues/797

**Comment by xpepermint** [comment]
Perfect!
