### ISSUE TITLE
Support importing fragments

### ISSUE THREAD

**Issue by majodev** [kumarharsh/graphql-for-vscode#22]
Enhancement, see documentation in [gql-tag](https://github.com/apollographql/graphql-tag/pull/33).

**Comment by kumarharsh** [comment]
@majodev - from what I read, this is a webpack feature rather than an editor feature. Can you clarify exactly what you mean?

**Comment by majodev** [comment]
Sure, this allows to import fragments from other files, however to plugin does not understand the import syntax, which leads to `NoUnusedFragments` and `KnownFragmentNames` errors.

See the attached screenshot.
<img width="1204" alt="bildschirmfoto 2017-03-31 um 12 02 20" src="https://cloud.githubusercontent.com/assets/2149883/24546046/f127ef3a-1609-11e7-8e55-52f4415dcae4.png">

**Comment by kumarharsh** [comment]
OK, I understand, thanks for the screenshot too. I'll look into how to do this.

**Comment by kumarharsh** [comment]
I think the [gql repo](https://github.com/Mayank1791989/gql) will be the best place to handle this.

**Comment by kumarharsh** [comment]
This can be solved by following the suggestions mentioned here:

https://github.com/Mayank1791989/gql/issues/3#issuecomment-332317671

**Comment by maapteh** [comment]
Even when added as normal typescript files and added to the section it's still not supported to have fragments? (error: KnownFragmentNames) Can it be added?

```
export const FRAGMENT_PRODUCT = gql`
    fragment product on Product {
        id
```
