### ISSUE TITLE
I'm doing something dumb I think - syntax highlighting not working?

### ISSUE THREAD

**Issue by sunscreem** [kumarharsh/graphql-for-vscode#227]
![image](https://user-images.githubusercontent.com/7523595/71633497-5ecdd980-2c0c-11ea-80b3-4452247e0f7f.png)

As you can see - the query isn't being highlighted. But then again - why would it? VS code doesn't know this is graph ql code. If I add `gql` before the ` then it works, but it throws a run time error.

**Comment by kumarharsh** [comment]
You can use the comment syntax to tell the syntax highlighter that this is a graphql block.

```js
const query = /* GraphQL */`
  ... your query ...
`;
```

**Comment by sunscreem** [comment]
Thank you sir!

**Comment by kumarharsh** [comment]
You're welcome :)
