### ISSUE TITLE
Syntax error when a type implements multiple interfaces or descriptions are used   

### ISSUE THREAD

**Issue by Daviziu** [kumarharsh/graphql-for-vscode#240]
There are two instances where the correct GraphQL syntax is used but the extension gives an error which also breaks inspection/autocomplete in other files.

1) **Multiple Interfaces**
related to #32 
```graphql
type User implements Human & Named {
   name: String!
   hobbies: [String!]!
}

interface Human {
   hobbies: [String!]!
}

interface Named {
   name: String!
}
```
In this case the ampersand symbol is highlighted and the following error is displayed.
![Bildschirmfoto 2020-01-30 um 14 33 24](https://user-images.githubusercontent.com/8290669/73454117-b4151c00-436d-11ea-9814-70e75d1f4ed6.png)

It works by replacing `&` with commas, but that is not the correct syntax and therefore those schemas would not work anywhere else.

2) **Descriptions**
```graphql
"""A User"""
type User implements Human {
   name: String!
   hobbies: [String!]!
}
```
Descriptions are used for documentation and are usually made using three double quotes (however I think single double quotes work too). And descriptions can be one ore multiple lines. With the upper code I get the following error:
![Bildschirmfoto 2020-01-30 um 14 39 08](https://user-images.githubusercontent.com/8290669/73454394-4fa68c80-436e-11ea-8baf-02f6c452ef48.png)

**Comment by kumarharsh** [comment]
It's an issue of the underlying language server. Can you please file it at https://github.com/Mayank1791989/gql/issues
