### ISSUE TITLE
request feature: autocomplete as we type

### ISSUE THREAD

**Issue by ticruz38** [kumarharsh/graphql-for-vscode#27]
That plugin is truly awesome.
That would be even better though to have autocomplete when writing queries. Pretty much like in graphiql.
Currently we got the errors on query field when saved.

**Comment by kumarharsh** [comment]
The autocomplete is already there. Press Ctrl+Space for suggestions.

**Comment by ticruz38** [comment]
Damn you're right! totally awesome
