### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by Crevil** [kumarharsh/graphql-for-vscode#3]
Make changes more clear by adding a `CHANGELOG.md` to the root. This enables the extension explorer to show changes and make the project progress more transparent.

This was enabled in the October VS Code 1.7 release: https://code.visualstudio.com/updates#_changelogs

**Comment by kumarharsh** [comment]
Thank you @Crevil for the suggestion. The Changelog.md file is already there (in `client/` folder). I forgot to add the last change into the changelog though... 😄

**Comment by Crevil** [comment]
@kumarharsh Ah, missed that. NVM.
