### ISSUE TITLE
Request to add disable line feature

### ISSUE THREAD

**Issue by gaoxiaoliangz** [kumarharsh/graphql-for-vscode#31]
When writing graphql queries, I often have to import external gql files and use them as fragments, like so:

```js
const withData = graphql(gql`
  query queryBooks($id: ID!) {
    book(id: $id) {
      ...BookInfo
    }
  }
  ${BOOK_INFO}
`, {
    options: (props) => {
      return {
        variables: {
          id: props.params.id
        }
      }
    }
  })
```
but the plugin give me '[graphql] Syntax Error: Unexpected $' error. I know it seems to be an error for the plugin, but in the real world, it works fine, so how to disable that line of linting so it would not produce errors like that?

**Comment by kumarharsh** [comment]
@gaoxiaoliangz thank you for the report. The plugin shouldn't be throwing this error, as the interpolation you're doing is perfectly valid. I'm myself writing components like so:
![image](https://cloud.githubusercontent.com/assets/760112/26783398/93a7908c-4a15-11e7-9611-252c893c8165.png)

Please make sure that you're using the latest [gql library](https://github.com/Mayank1791989/gql). If you get this error even after updating, then can you give me a small example project which can reproduce this error?

**Comment by Mayank1791989** [comment]
Actually, the plugin will throw an error as [gql](https://github.com/Mayank1791989/gql) parser only support interpolation inside operations and fragments (relay style) not outside as in apollo.

**Comment by Mayank1791989** [comment]
This issue was moved to Mayank1791989/gql#28
