### ISSUE TITLE
Doesn't work with schema path outside project root

### ISSUE THREAD

**Issue by peterholak** [kumarharsh/graphql-for-vscode#33]
```
schema: {
    files: '../graphql/*.graphql'
}
```

doesn't work, while

```
schema: {
    files: 'graphql/*.graphql'
}
```

works just fine.

Using it on Windows 10, not sure how to get any useful error message (I just see an error icon in VSCode and the plugin features don't work).

**Comment by kumarharsh** [comment]
This plugin was designed with the expectation that the graphql files would be included with the project and checked into source control - you'll also need to put the `.gqlconfig` file in the root of your project. May I know about your use case?

**Comment by peterholak** [comment]
I have a project where both the client and the server (multiple different servers in fact) are in the same git repository, and share the same graphql schema. So the directory structure goes something like

    |- client
        |- package.json
        |- webpack.config.js
        |- ...
    |- server1
    |- server2
    |- graphql
        |- schema.graphql
    |- README.md and other stuff

In VSCode, I only open the `client` directory, because it's more convenient (no irrelevant clutter when doing project-wide search, correct default working directory for scripts, etc.).

**Comment by kumarharsh** [comment]
Got it.

**Comment by kumarharsh** [comment]
So, I looked into the related gql project internals, and it uses minimatch for matching your paths. Minimatch [doesn't support](https://github.com/isaacs/minimatch/issues/30) specifying `..` in the path. I think we can do a fix on our end to handle relative paths with `..` in some special way.

**Comment by peterholak** [comment]
I wonder if it's even worth fixing with the dependencies being how they are...

**Comment by kumarharsh** [comment]
I've figured out how to fix it on my side, not sure if watchman supports it though... The docs are a little lacking - I'll dig there some more. Just a quick question @peterholak, your `client` and `server1`, `server2`... folders are all nested within the same root folder. Is the root folder the **git** root too? Does the  `.git` folder lie in the root folder, or in each subfolder?

**Comment by peterholak** [comment]
Just one `.git` in the root folder.

**Comment by kumarharsh** [comment]
I think this feature might be possible after [this is resolved](https://github.com/Mayank1791989/gql/issues/62#issuecomment-330945526).
