### ISSUE TITLE
GraphQL suggestions have a low priority in autocomplete within JS files

### ISSUE THREAD

**Issue by saborrie** [kumarharsh/graphql-for-vscode#38]
I created a new react app using 'create-react-app' and then added these type definitions to the appropriate places in `.gqlconfig`: 

```graphql
type Query {
  sensors: [Sensor]
}

type Sensor {
  datapoints: [Data]
}

type Data {
  x: Int
  y: Int
}

```

Everything is working as it should except that the GraphQL query suggestions are at the very bottom of the autocomplete list:

![image](https://user-images.githubusercontent.com/4096734/29870205-458b0576-8d7e-11e7-94a2-fbd2f083f768.png)

**Comment by saborrie** [comment]
Perhaps also the list of snippets/suggestions that are for JavaScript should not show up, if that's possible

**Comment by kumarharsh** [comment]
Thanks for the report. I'll see if I can influence the sort order in some way.

I have snippets usually turned off in the autocomplete list, and invoke them separately with a different keybinding because I found that I rarely used even 5% of the default JS snippets.

**Comment by kumarharsh** [comment]
Apparently, the ordering can't be influenced by plugins in any way. You can control the autocomplete suggestions on your end via settings.
See this issue: https://github.com/Microsoft/vscode/issues/9286 and related ones for more details.
