### ISSUE TITLE
Support for `.graphqlrc` files

### ISSUE THREAD

**Issue by StevenLangbroek** [kumarharsh/graphql-for-vscode#40]
There's a [parser](https://www.npmjs.com/package/graphql-config-parser) available on `npm`. It allows fetching a schema from an endpoint, which automates a whole bunch of manual wiring you'd have to normally maintain (exporting & importing Schemas). Would you be open to implementing this? And if so: how can I help? :)

**Comment by kumarharsh** [comment]
@StevenLangbroek - the config file reading logic is in the related [gql](https://github.com/Mayank1791989/gql) repo. Looping @Mayank1791989 in.

**Comment by jaydenseric** [comment]
The latest iteration is [`graphql-config`](https://www.npmjs.com/package/graphql-config) and `.graphqlconfig` files.

I already have a lot of other tools using it; I would consider using this package once `.graphqlconfig` is adopted. That, and when linting is removed and left to `eslint-plugin-graphql` ([#30](https://github.com/kumarharsh/graphql-for-vscode/issues/30)).

**Comment by schickling** [comment]
@kumarharsh any progress on supporting `graphql-config`? (We're currently recommending people to use [vscode-graphql](https://github.com/stephen/vscode-graphql) until graphql-for-vscode supports graphql-config.)

**Comment by kumarharsh** [comment]
@schickling sorry, have been on vacation. I'll have something to say about it this week.

**Comment by Mayank1791989** [comment]
see issue https://github.com/Mayank1791989/gql/issues/90
