### ISSUE TITLE
Mark js/ts query strings as language:graphql

### ISSUE THREAD

**Issue by mjbvz** [kumarharsh/graphql-for-vscode#43]
**Problem**
Graphql template strings are currently marked as `language: javascript`

![screen shot 2017-09-18 at 1 20 42 pm](https://user-images.githubusercontent.com/12821956/30562715-55458f18-9c74-11e7-9901-b75d81b3117f.png)

It should be `css` instead. The language mode effects editor features such as bracket matching.

**Fix**
VSCode has an `embeddedLanguages` setting that marks language mode within a grammar.  We just added support for using `embeddedLanguages` with an injected grammar: https://github.com/Microsoft/vscode/issues/34316

I'll submit a PR that does this for this extension

**Comment by kumarharsh** [comment]
thanks @mjbvz. I was keenly following the discussion in the vscode repo about embeddedlanguages. Good to see it land so quickly 👍

**Comment by kumarharsh** [comment]
@mjbvz is the implementation for this feature in vscode *complete*, or is it pending some review? I can verify that the code works in the latest insider. Just want to ensure the embeddedLanguages feature is officially supported before shipping.

**Comment by mjbvz** [comment]
Thanks! Yes the embeddedLanguages went out with a recent insiders build and we plan on rolling it with the official VS Code 1.17 release at the start of October. The feature will only work in VS Code 1.17+ but should not regress earlier versions of code
