### ISSUE TITLE
Support for multi-folder workspaces

### ISSUE THREAD

**Issue by felixfbecker** [kumarharsh/graphql-for-vscode#46]
Seems like when using this plugin with multi-folder workspaces, it cannot find the .gqlconfig file

![image](https://user-images.githubusercontent.com/10532611/31003227-6b74ec8e-a4a3-11e7-93ee-64b42cf8447d.png)

```
[Info  - 23:18:56] NODE_PATH value is: /Users/felix/.nvm/versions/node/v8.4.0/lib/node_modules
[Info  - 23:18:56] Module '@playlyfe/gql' loaded from: /Users/felix/.nvm/versions/node/v8.4.0/lib/node_modules/@playlyfe/gql/lib/index.js
[Error - 23:18:56] Server initialization failed:
Request initialize failed with message: Could not find a .gqlconfig file. Create a .gqlconfig file in project root directory.
```

**Comment by felixfbecker** [comment]
This works for me now

**Comment by bradleyayers** [comment]
Is it supposed to work when you have multiple `.gqlconfig` files (e.g. one in each workspace directory)?

**Comment by galvesribeiro** [comment]
So, any updates on this?

**Comment by kumarharsh** [comment]
It has arrived in the latest version. 🎉

**Comment by HosseinAgha** [comment]
@kumarharsh I'm on `1.15.1` and this is not working for me. Should I create VSCode workspace for each project in monorepo for this to work?

**Comment by Mayank1791989** [comment]
Yes and you need config file in root of workspace folder.

**Comment by HosseinAgha** [comment]
As far as I know it is not possible to use vscode workspaces with a monorepo setup (take a look at [apollo server](https://github.com/apollographql/apollo-server)) as you need the root directory in your workspaces and [vscode does not support nested workspaces](https://github.com/microsoft/vscode/issues/45470)

**Comment by Mayank1791989** [comment]
I am planning to implement the multi project support something similar to how I implemented in flow-for-vscode plugin that will solve the mono repo issue. But for now you can make all individual gqlconfig folder as vscode workspace folder.
