### ISSUE TITLE
Unknown directive "argumentDefinitions", "arguments"

### ISSUE THREAD

**Issue by voxmatt** [kumarharsh/graphql-for-vscode#48]
I get the error `[graphql] Unknown directive "argumentDefinitions". (KnownDirectives)` on a few of the `graphql.experimental` directives. Specifically, `@argumentDefinitions` and `@arguments`

These are used by Relay-Modern and I'd love support for them.

**Comment by Mayank1791989** [comment]
see issue https://github.com/Mayank1791989/gql/issues/52

**Comment by voxmatt** [comment]
Ah, great. Sorry, I did search the issues first but missed this one. Thanks!
