### ISSUE TITLE
Autocomplete for Types and Fields of my Schema in Queries

### ISSUE THREAD

**Issue by pungggi** [kumarharsh/graphql-for-vscode#49]
I am writing this because I still dont understand if it is a bug or I did not unterstand the !Autocompletion feature.

I have config file
![image](https://user-images.githubusercontent.com/5635709/31579262-c7d9ec0e-b132-11e7-9e47-40b65a310faf.png)

It recognizes my path, even the template literals, but the suggestion it makes is 
![image](https://user-images.githubusercontent.com/5635709/31579304-f4917e82-b133-11e7-922d-91edf7d1482f.png)

I was also expecting **my Types and Fields to be suggested** after I am in the query?

Opened also https://github.com/Mayank1791989/gql/issues/67

**Comment by kumarharsh** [comment]
Already being discussed in Mayank1791989/gql#67
