### ISSUE TITLE
GQL:Graphql Server hasstopped

### ISSUE THREAD

**Issue by ganeshpms** [kumarharsh/graphql-for-vscode#51]
![gql](https://user-images.githubusercontent.com/5632736/31977998-fc439592-b904-11e7-81db-699014cb8e64.jpg)
After installing and configured as instructed, the .gql file is not getting the autocomplete or F12 reference. Also in the status bar, it says"Graph QL Server has stopped". Any suggestion to resolve this issue?

**Comment by Mayank1791989** [comment]
Please share your .gqlconfig and sample .gql file.

**Comment by ganeshpms** [comment]
Uploaded the file.  [ please note I am using Windows]
[.gqlconfig.txt](https://github.com/kumarharsh/graphql-for-vscode/files/1415617/default.gqlconfig.txt)


[job.gql.txt](https://github.com/kumarharsh/graphql-for-vscode/files/1415622/job.gql.txt)
[schema.gql.txt](https://github.com/kumarharsh/graphql-for-vscode/files/1415623/schema.gql.txt)

**Comment by Mayank1791989** [comment]
You have to modify .gqlconfig file according to your project (.gqlconfig in readme is sample config). If you can share your project structure I can help you in that.

**Comment by ganeshpms** [comment]
It is working when I try to set a sample project. Thanks for your help.
