### ISSUE TITLE
string interpolation cause syntax error with type Int

### ISSUE THREAD

**Issue by sandangel** [kumarharsh/graphql-for-vscode#56]
I have a request with dynamic inject Int value into it by string interpolation like so
![image](https://user-images.githubusercontent.com/22189661/33246004-f03f7d16-d352-11e7-88d7-b83009805a07.png)

With String type, there is no problem since it is wrapped in double quote (although there is no syntax highlighting with string interpolation but it show no error)

**Comment by kumarharsh** [comment]
Thanks for the report. @Mayank1791989 would you have a look?

**Comment by Mayank1791989** [comment]
@sandangel for dynamic values you should use graphql variables.
```js
const query = gql`
  mutation reportIotData($unixTime: Int!, $env: String!) {
    reportIotData(
      device: {
        iotAddress: ""
        unixTime: $unixTime
        username: ""
        piSerial: ""
      }
      env: $env
    )
  }
`;
```

**Comment by sandangel** [comment]
you mean that string interpolation is not a valid use case?

**Comment by Mayank1791989** [comment]
For static validation of queries its better to avoid interpolation. Currently parser only support interpolation in few places like fragment interpolation for relay-classic client and query interpolation for apollo client.

**Comment by sandangel** [comment]
Thanks. I will close this issue but I hope that you could improve support on string interpolation later, because I think it's shorter and more elegance than using variables
