### ISSUE TITLE
Error when viewing .gql file

### ISSUE THREAD

**Issue by yurigenin** [kumarharsh/graphql-for-vscode#6]
[Error - 12:36:21 PM] Server initialization failed.
  Message: Request initialize failed with message: Could not find a .gqlconfig file. Create a .gqlconfig file in project root directory.
  Code: -32603

**Comment by kumarharsh** [comment]
@yurigenin thank you for the report. I forgot to mention this in the readme. The playlyfe/gql package requires a .gqlconfig file to function. I'll make some changes soon.

**Comment by kumarharsh** [comment]
Related issue: https://github.com/Microsoft/vscode/issues/2793

**Comment by kumarharsh** [comment]
Related issue: https://github.com/Microsoft/vscode/issues/6858#issuecomment-221801714

**Comment by kumarharsh** [comment]
I think it'll be "properly" fixed only when v8 ships with lookbehind support: http://v8project.blogspot.in/2016/02/regexp-lookbehind-assertions.html?m=1

**Comment by ackzell** [comment]
Hey @kumarharsh, awesome extension! Thanks a lot for your work.

I am wondering what the .gqlconfig file should look like?

I think all I'm getting from the extension is syntax highlight and a couple snippets, but not the rest.

**Comment by kumarharsh** [comment]
@ackzell - the .gqlconfig file is actually needed by the [@playlyfe/gql](https://github.com/Mayank1791989/gql) plugin this is based off. The .gqlconfig is a JSON-ish file with only one key which is required: `schema.files` which is the path to your `*.gql` files relative to your workspace root.

example:
```js
/* .gqlconfig */
{
  schema: {
    files: "schemas/**/*.gql"
  }
}
```

**Comment by ackzell** [comment]
Great, thanks. 

I went into the _@playly/gql_ project but couldn't find the syntax.

Works like a charm!

**Comment by afduarte** [comment]
I recommend these instructions and the example .gqlconfig are moved to the readme file, just spent a massive amount of time only trying to configure the plugin

**Comment by kumarharsh** [comment]
@afduarte I completely agree. I just haven't found time this week for this. I'll push an update as soon as I get some time (probably tomorrow).

**Comment by afduarte** [comment]
Should I just submit a Pull Request? I'll do it if I have time

**Comment by kumarharsh** [comment]
Sure, that'd be great
