### ISSUE TITLE
trouble getting it working

### ISSUE THREAD

**Issue by DogsForArms** [kumarharsh/graphql-for-vscode#60]
Hello!  I am very excited to use this plugin but after following the installation instructions very closely I am still not able to get my vsc autocompletion for my gql`` queries.

I have noticed that my schema.gql is working right with autocompletion/errors/jump to definition.  But, in my client gql`` style queries do not autocomplete or error check - however their colors look right.

my .gqlconfig looks like:

```
{
   schema: {
     files: 'schemas/**/*.gql'
   },
   query: {
        files: [ 
            {
                match: 'src/**/*.ts',
                parser: ['EmbeddedQueryParser', { startTag: 'gql`', endTag: '`' }]
            },
            {
                match: 'src/**/*.tsx',
                parser: ['EmbeddedQueryParser', { startTag: 'gql`', endTag: '`' }]
            }
        ]
    }
}
```

Some info: 

vscode 1.81.1
@playlyfe/gql 2.3.2 (installed in my project's root node_modules)

My relevant folder structure: 

- schemas
   - schema.gql 
- node_modules
   - @playlyfe/gql
- src/
     **/ *.tsx, ts
.gqlconfig

here is the output from >graphqlForVSCode.showOutputChannel
```
[Info  - 23:37:57] NODE_PATH value is: /Users/ethan/Documents/LoMo/Navi
[Info  - 23:37:57] Module '@playlyfe/gql' loaded from: /Users/ethan/Documents/LoMo/Navi/node_modules/@playlyfe/gql/lib/index.js
[vscode] File extensions registered:  [ 'gql', 'ts', 'tsx' ]
[Watch established (gqlSchemaFiles)] 
	basePath: /Users/ethan/Documents/LoMo/Navi 
	RelativePath: undefined 
	Files: "schemas/**/*.gql"
[Watch established (gqlQueryFiles-0)] 
	basePath: /Users/ethan/Documents/LoMo/Navi 
	RelativePath: undefined 
	Files: "src/**/*.ts"
[Watch established (gqlQueryFiles-1)] 
	basePath: /Users/ethan/Documents/LoMo/Navi 
	RelativePath: undefined 
	Files: "src/**/*.tsx"
```
So it seems like it is watching at least.

Thanks for your time!

**Comment by DogsForArms** [comment]
Of course it started working by itself right after I posted :) Probably I just needed to restart VSC.

**Comment by holmesal** [comment]
Dogs for arms! Dogs for arms!

**Comment by kumarharsh** [comment]
@holmesal what?
