### ISSUE TITLE
Syntax Highlighting Issues

### ISSUE THREAD

**Issue by kumarharsh** [kumarharsh/graphql-for-vscode#62]
the template literals highlighting isn't working for me, do I have to do anything special?

I have `@playlyfe/gql` installed globally, and the config set to`"graphqlForVSCode.nodePath": "~/.config/yarn/global/node_modules"`.

I also have the `.gqlconfig` file in my project folder (under `/apps/web/.gqlconfig`).

The `.gql` files are highlighted.

> Reported by @FezVrasta on Dec 21, 2017, 4:04 PM GMT+5:30

**Comment by kumarharsh** [comment]
Can you share a file which is not working? I'd like to take a look.

**Comment by kumarharsh** [comment]
any file, even ones with just

```
import gql from 'graphql-tag';
gql`
  query {
    name
  }
`
```

**Comment by kumarharsh** [comment]
any file, even ones with just

```
import gql from 'graphql-tag';
gql`
  query {
    name
  }
`
```

**Comment by kumarharsh** [comment]
@FezVrasta

I tried with "Javascript" and "Javascript React", I haven't any plugin I could simply turn off without lose anything I use daily, I think the extension should play nicely with the other extensions, otherwise it doesn't make much sense to me.

**Comment by kumarharsh** [comment]
Yes, I agree. I just want to get more information so that I can trace which part is conflicting. Can you disable all extensions, and then enable only this one, and do a "Reload Window"?

![image](https://user-images.githubusercontent.com/760112/34255639-9c299fa8-e677-11e7-8190-643e7f691e7d.png)

![image](https://user-images.githubusercontent.com/760112/34255656-b1a3377c-e677-11e7-84ac-916d42874a73.png)
![image](https://user-images.githubusercontent.com/760112/34255664-c3c1475a-e677-11e7-80c4-7d74454ba5c3.png)

See if you get the highlighting?

**Comment by kumarharsh** [comment]
I reinstalled and configured it, with all the extensions disabled, the minimal example works, but any other file in my project still misses the syntax highlight.

It looks like the syntax doesn't work if I provide the second argument to `graphql`:

```
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
graphql(
  gql`
    query {
      name
    }
  `,
  {}
);
```

**Comment by kumarharsh** [comment]
So, you're saying that if your remove the last two lines, the highlighting **is** working?
That's odd :/ Which theme are you using?

**Comment by FezVrasta** [comment]
It's enough to remove this:

```
,
  {}
```

I'm using City Lights as theme

**Comment by kumarharsh** [comment]
Can you share the theme URL? I can't find it via VSCode's search

**Comment by FezVrasta** [comment]
http://citylights.xyz/

**Comment by kumarharsh** [comment]
Seems to be working for me without any hiccup:

![gif](https://user-images.githubusercontent.com/760112/34257004-fcd08afa-e67d-11e7-925f-23daa941ca2b.gif)

(don't focus on the bracket colours - they are from bracket pair colorizer)

Can you do an `Inspect Scopes` in your code to see the scopes being applied to your graphql code within the `gql` tag? Share some screenshots of the scopes too.

![image](https://user-images.githubusercontent.com/760112/34257102-748cd206-e67e-11e7-9e0e-89b052924542.png)

![image](https://user-images.githubusercontent.com/760112/34257091-6d902cb4-e67e-11e7-9327-fd5cf8ff30a8.png)

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/34257184-09ab3e98-e659-11e7-842b-01b22821a85d.png)
![image](https://user-images.githubusercontent.com/5382443/34257193-12ff9386-e659-11e7-8c1e-aec3cc536414.png)

**Comment by FezVrasta** [comment]
![noidea](https://user-images.githubusercontent.com/5382443/34257291-8e7527f6-e659-11e7-92ad-861976ad9df6.gif)

now it's behaving differently than before.... even without the second argument it doesn't work as soon I indent it.

It may be just me, but this extension doesn't look that stable to me 😔

**Comment by kumarharsh** [comment]
Wow, the plugin hasn't even activated (notice - there is no graphql scope injected). Are you on an insider build of vscode?

**Comment by kumarharsh** [comment]
If you rename `graphql(` to `zraphql(`, does the highlighting work?

**Comment by FezVrasta** [comment]
Unfortunately I have already deleted the test file and now that I created it again the problem I showed in the gif doesn't reproduce anymore... But I have this now:

![noidea2](https://user-images.githubusercontent.com/5382443/34257637-fedb6a9a-e65a-11e7-8a26-b8bfdb1517a6.gif)

**Comment by FezVrasta** [comment]
And also this:

![noidea3](https://user-images.githubusercontent.com/5382443/34257754-6f177a9c-e65b-11e7-9c1f-c8e5c7266566.gif)

**Comment by kumarharsh** [comment]
Thanks for all the effort @FezVrasta, and it sucks that the extension is not working well for you. It's extremely odd and unexpected :-/

I'll keep looking for a way to reproduce it on my machine. Maybe there's some bug with vscode too, but we'll not know that until we can get a reproduction.

Can you share your OS, Vscode Build number (Help > About > Copy), and list of currently installed extensions?

**Comment by FezVrasta** [comment]
iMac (Retina 5K, 27-inch, Late 2014)
macOS High Sierra 10.13.2 (17C88)
VSCode 1.19.1 (1.19.1) - 0759f77bb8d86658bc935a10a64f6182c5a1eeba


```
[
  {
    "metadata": {
      "id": "fa57ae0e-d21e-40d8-a0bb-a58b5fd9ead3",
      "publisherId": "ms-vscode.atom-keybindings",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "atom-keybindings",
    "publisher": "ms-vscode",
    "version": "3.0.2"
  },
  {
    "metadata": {
      "id": "819a23e1-b6c6-41cf-9029-e653b537d996",
      "publisherId": "ms-vscode.azure-account",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "azure-account",
    "publisher": "ms-vscode",
    "version": "0.2.2"
  },
  {
    "metadata": {
      "publisherId": "yummygum.city-lights-theme",
      "publisherDisplayName": "yummygum"
    },
    "name": "city-lights-theme",
    "publisher": "yummygum",
    "version": "1.0.0"
  },
  {
    "metadata": {
      "id": "e337c67b-55c2-4fef-8949-eb260e7fb7fd",
      "publisherId": "Shan.code-settings-sync",
      "publisherDisplayName": "Shan"
    },
    "name": "code-settings-sync",
    "publisher": "Shan",
    "version": "2.8.6"
  },
  {
    "metadata": {
      "id": "1ec62ca5-d7f9-4ddb-a882-e8d018c0aefd",
      "publisherId": "msjsdiag.debugger-for-chrome",
      "publisherDisplayName": "msjsdiag"
    },
    "name": "debugger-for-chrome",
    "publisher": "msjsdiag",
    "version": "3.5.0"
  },
  {
    "metadata": {
      "id": "f60a60a6-95ba-42d4-b41c-3d24c1b89588",
      "publisherId": "EditorConfig.EditorConfig",
      "publisherDisplayName": "EditorConfig"
    },
    "name": "EditorConfig",
    "publisher": "EditorConfig",
    "version": "0.11.1"
  },
  {
    "metadata": {
      "id": "76bffba6-8ba8-4728-9ecc-02a7c233d841",
      "publisherId": "bigous.file-smart-reopener-vscode",
      "publisherDisplayName": "bigous"
    },
    "name": "file-smart-reopener-vscode",
    "publisher": "bigous",
    "version": "0.0.1"
  },
  {
    "metadata": {
      "id": "b3917e4f-5086-4def-a82b-2ae6b708db16",
      "publisherId": "flowtype.flow-for-vscode",
      "publisherDisplayName": "flowtype"
    },
    "name": "flow-for-vscode",
    "publisher": "flowtype",
    "version": "0.7.2"
  },
  {
    "metadata": {
      "id": "6333012c-5de4-4955-ade9-77c630e471fc",
      "publisherId": "joshjg.generate-react-component",
      "publisherDisplayName": "joshjg"
    },
    "name": "generate-react-component",
    "publisher": "joshjg",
    "version": "0.2.1"
  },
  {
    "metadata": {
      "id": "2bba45f2-4a48-41a6-bb86-d6ba5ab29a9f",
      "publisherId": "felipecaputo.git-project-manager",
      "publisherDisplayName": "felipecaputo"
    },
    "name": "git-project-manager",
    "publisher": "felipecaputo",
    "version": "1.4.0"
  },
  {
    "metadata": {
      "id": "4de763bd-505d-4978-9575-2b7696ecf94e",
      "publisherId": "eamodio.gitlens",
      "publisherDisplayName": "eamodio"
    },
    "name": "gitlens",
    "publisher": "eamodio",
    "version": "6.1.1"
  },
  {
    "metadata": {
      "id": "93ecc089-f396-47b4-8676-7fa3bc156a2c",
      "publisherId": "sysoev.language-stylus",
      "publisherDisplayName": "sysoev"
    },
    "name": "language-stylus",
    "publisher": "sysoev",
    "version": "1.8.0"
  },
  {
    "metadata": {
      "id": "7f147721-ec06-4043-9e37-c9ffbecbccd1",
      "publisherId": "whizkydee.material-palenight-theme",
      "publisherDisplayName": "whizkydee"
    },
    "name": "material-palenight-theme",
    "publisher": "whizkydee",
    "version": "1.6.0"
  },
  {
    "metadata": {
      "id": "26a529c9-2654-4b95-a63f-02f6a52429e6",
      "publisherId": "zhuangtongfa.Material-theme",
      "publisherDisplayName": "zhuangtongfa"
    },
    "name": "Material-theme",
    "publisher": "zhuangtongfa",
    "version": "2.10.22"
  },
  {
    "metadata": {
      "id": "a41c1549-4053-44d4-bf30-60fc809b4a86",
      "publisherId": "christian-kohler.path-intellisense",
      "publisherDisplayName": "christian-kohler"
    },
    "name": "path-intellisense",
    "publisher": "christian-kohler",
    "version": "1.4.2"
  },
  {
    "metadata": {
      "id": "b3424f3a-d5cb-44d1-aa93-5095b5e6287b",
      "publisherId": "mhmadhamster.postcss-language",
      "publisherDisplayName": "mhmadhamster"
    },
    "name": "postcss-language",
    "publisher": "mhmadhamster",
    "version": "2.0.2"
  },
  {
    "metadata": {
      "id": "96fa4707-6983-4489-b7c5-d5ffdfdcce90",
      "publisherId": "esbenp.prettier-vscode",
      "publisherDisplayName": "esbenp"
    },
    "name": "prettier-vscode",
    "publisher": "esbenp",
    "version": "0.24.0"
  },
  {
    "metadata": {
      "id": "f8b5562e-a2d9-49ab-9f91-e7da91998a92",
      "publisherId": "shinnn.stylelint",
      "publisherDisplayName": "shinnn"
    },
    "name": "stylelint",
    "publisher": "shinnn",
    "version": "0.30.0"
  },
  {
    "metadata": {
      "id": "80f8708c-d467-4ed5-8582-203619bb0345",
      "publisherId": "gerane.Theme-Aurora",
      "publisherDisplayName": "gerane"
    },
    "name": "Theme-Aurora",
    "publisher": "gerane",
    "version": "0.0.2"
  },
  {
    "metadata": {
      "id": "7a21e2ae-a6dd-4666-b31d-871b4862f214",
      "publisherId": "eamodio.toggle-excluded-files",
      "publisherDisplayName": "eamodio"
    },
    "name": "toggle-excluded-files",
    "publisher": "eamodio",
    "version": "1.6.0"
  },
  {
    "metadata": {
      "id": "d7b592dd-41c9-4f2b-acf3-055ae65e55c6",
      "publisherId": "dzannotti.vscode-babel-coloring",
      "publisherDisplayName": "dzannotti"
    },
    "name": "vscode-babel-coloring",
    "publisher": "dzannotti",
    "version": "0.0.4"
  },
  {
    "metadata": {
      "id": "0479fc1c-3d67-49f9-b087-fb9069afe48f",
      "publisherId": "PeterJausovec.vscode-docker",
      "publisherDisplayName": "PeterJausovec"
    },
    "name": "vscode-docker",
    "publisher": "PeterJausovec",
    "version": "0.0.22"
  },
  {
    "metadata": {
      "id": "583b2b34-2c1e-4634-8c0b-0b82e283ea3a",
      "publisherId": "dbaeumer.vscode-eslint",
      "publisherDisplayName": "dbaeumer"
    },
    "name": "vscode-eslint",
    "publisher": "dbaeumer",
    "version": "1.4.3"
  },
  {
    "metadata": {
      "id": "ee33fd31-7bb4-4252-8368-fdd5bcd94cf8",
      "publisherId": "akamud.vscode-theme-onelight",
      "publisherDisplayName": "akamud"
    },
    "name": "vscode-theme-onelight",
    "publisher": "akamud",
    "version": "2.1.0"
  }
]
```

**Comment by Mayank1791989** [comment]
The problem is in plugin _dzannotti.vscode-babel-coloring_. Please remove (or disable) plugin to fix your issue. If you want es6|es7 support use [sublime-babel ](https://github.com/joshpeng/Sublime-Babel-VSCode) plugin instead.

**Comment by kumarharsh** [comment]
@fezvrasta can you confirm if this works?

**Comment by kumarharsh** [comment]
I can confirm that the vscode-babel-coloring plugin is the one causing issues:

With vscode-babel-coloring:
![gif](https://user-images.githubusercontent.com/760112/34287981-924410e2-e710-11e7-8bb2-346c9f8a80e2.gif)

With sublime-babel:
![gif2](https://user-images.githubusercontent.com/760112/34288017-d28e8c22-e710-11e7-82c0-b2a3354d9f4a.gif)

**Comment by FezVrasta** [comment]
Yes, it seems to work fine now, thanks.

**Comment by kumarharsh** [comment]
Glad to hear it. I'd recommend using sublime-babel as it's the most full-featured one for vscode (till now). The vscode-babel plugin hasn't been updated for a long time.

**Comment by kachkaev** [comment]
Is syntax highlighting expected to work with comment-prefixed strings?

```js
export default /* GraphQL */ `
# graphql types etc. (expected to be highlighted)
`;
```

Used to have this [working](https://github.com/gandm/language-babel#graphql-code-highlighting) in Atom with language-babel package.
