### ISSUE TITLE
Support new description syntax

### ISSUE THREAD

**Issue by jlengstorf** [kumarharsh/graphql-for-vscode#63]
As of [v0.12.0](https://github.com/graphql/graphql-js/releases/tag/v0.12.0), field descriptions need to be represented as strings rather than comments.

That means that the following schema:

```graphql
type Query {
  # Receive a greeting.
  hello: String
}
```

Needs to be rewritten as:

```graphql
type Query {
  """
  Receive a greeting.
  """
  hello: String
}
```

Syntax highlighting should be updated to reflect the string type; right now it looks pretty wonky.

<img width="573" alt="screencap-by-jlengstorf 26" src="https://user-images.githubusercontent.com/163561/34314990-67a8b5e4-e72f-11e7-8ce4-136b19d46ec6.png">

**Comment by kumarharsh** [comment]
@jlengstorf thanks for the issue. Support for the new description syntax is in the latest release.

**Comment by tgriesser** [comment]
@kumarharsh Nice! was there a new release cut with this change, or is that still forthcoming?

**Comment by kumarharsh** [comment]
Yes, there was a new release.

**Comment by tgriesser** [comment]
I'm having trouble finding it. It seems to be missing on the [github releases tab](https://github.com/kumarharsh/graphql-for-vscode/releases) and it's not showing up under "More Info" on the [vscode project](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode).

**Comment by kumarharsh** [comment]
Yeah, it's stuck in publishing - apparently my Visual Studio Publish Token had expired and I'm weirdly locked out of the account from which the token was generated. I'm working to get things working again.

**Comment by kumarharsh** [comment]
Hi, I'm still not able to restore the publishing process and working on it.

Please try out this release, and let me know if things work fine:
https://1drv.ms/u/s!ArGqE3U0XhYmu5BCpISKDIQgbuMo9g

**Comment by tgriesser** [comment]
Yep, this works great. Good luck figuring out the publishing process 😕

**Comment by kumarharsh** [comment]
> Good luck figuring out the publishing process 😕

Yeah, it's a rabbit hole of accounts and permissions and what not 😟

**Comment by jlengstorf** [comment]
@kumarharsh I installed from the VSIX and it doesn't appear to support the string syntax:

<img width="775" alt="screencap-by-jlengstorf 49" src="https://user-images.githubusercontent.com/163561/34802706-a525f666-f634-11e7-8b2d-1354ca64df43.png">

Is there a setting I need to tweak?

**Comment by jlengstorf** [comment]
I believe this may be my fault, because I didn't include the single-line string syntax in the example above. Sorry about that! 😕

**Comment by tgriesser** [comment]
Ah yeah, it seems as though the [triple quote](https://github.com/graphql/graphql-js/blob/9b0d9ac5589cb5c70d53a0c9d6e60feca9c895b7/src/utilities/__tests__/buildASTSchema-test.js#L104) and [single quote](https://github.com/graphql/graphql-js/blob/9b0d9ac5589cb5c70d53a0c9d6e60feca9c895b7/src/utilities/__tests__/extendSchema-test.js#L138) should both be supported as valid single line descriptions - I only tried with the `"""` multi-line.

**Comment by kumarharsh** [comment]
I misread the linked issue and spec, they do state "any leading string".

**Comment by jlengstorf** [comment]
@kumarharsh Thanks for updating this! Is there a link to the new release and/or an ETA for it landing in the VS Code marketplace?

**Comment by kumarharsh** [comment]
Yes, it should be there now.

**Comment by Grmiade** [comment]
I have this syntax error. Is not The new description syntax is not supported?
(I use the 1.9.0 version of the extension)

<img width="473" alt="capture d ecran 2018-03-07 a 23 22 43" src="https://user-images.githubusercontent.com/11244106/37121761-7b2e332c-225e-11e8-84c6-2fd4429fe30d.png">

**Comment by tgriesser** [comment]
@Grmiade it's an issue with the `@playlyfe/gql` dependency - I opened a PR here https://github.com/Mayank1791989/gql/pull/111

**Comment by tgriesser** [comment]
In the meantime, if you want to specify: 
```
"@playlyfe/gql": "tgriesser/gql.git#upgrade-deps-published",
``` 
in your dependencies it should work. I'll keep that branch up until something gets merged upstream.

**Comment by Grmiade** [comment]
Thanks @tgriesser, indeed it works 👍
