### ISSUE TITLE
support /* GraphQL */ among other patterns

### ISSUE THREAD

**Issue by kachkaev** [kumarharsh/graphql-for-vscode#69]
When trying VSCode after Atom, I noticed that not all graphql scheama definitions are correctly found. Here's the one I struggled with:

```js
export default /* GraphQL */ `
# graphql types etc. (expected to be highlighted, but it did not)
`;
```

I guess this can be fixed by tweaking `begin` in `syntaxes/graphql.js.json`, which currently [equals to](https://github.com/kumarharsh/graphql-for-vscode/blob/3d6028b45fadfd1f89741bff307ce3fb28040a51/syntaxes/graphql.js.json#L8):

```js
"begin": "(Relay\\.QL|gql|graphql(\\.experimental)?)(`)",
``` 

In Atom's [language-babel](https://github.com/gandm/language-babel) package the definition of a similar concept [is a bit more complex](https://github.com/gandm/language-babel/blob/f1bcd82d1f0f8f151b64daf331fb017ce6540c72/grammars/Babel%20Language.json#L1112
):
```js
"begin": "\\s*+(?:((Relay)(?:(\\?\\.)|(\\.))(QL))|(gql|graphql|graphql\\.experimental)|(/\\* GraphQL \\*/))\\s*((`))",
```

In addition to `/* GraphQL */`, looks like the latter RegExp also supports spacing between a template literal and `` ` `` (e.g. both `` graphql` `` and `` graphql ` ``).

I'm not sure I'll be ready to submit a PR because I'm new to VSCode and won't find enough time to go through all potential difficulties of a newcomer. But still hope that my mini-investigation helps!

WDYT @kumarharsh? BTW thanks a lot for this handy extension! 💯

**Comment by kumarharsh** [comment]
It can be done, but I'm not entirely convinced of the usecase for this? Do you use this kind of definition in your code? Also, you can still trigger highlighting by adding a `#graphql` just after the opening backtick:

```js
export default `#graphql
  ...your graphql code here
`;
```

**Comment by kachkaev** [comment]
Thanks for hinting on ``export default `#graphql``! That's useful, but I guess it'd be still great to support `` /* GgraphQL */ ` `` too, at least because it's already supported by the Atom's package. Others switching to vscode may have similar expectations and get confused as well.

I've seen `` /* GgraphQL */ ` `` in a few places around github and I guess its' a convention of some sort (perhaps, even a wider one, not just GraphQL-specific).

**Comment by cjhowe7** [comment]
Note that `/* GraphQL */` is also used by the [VSCode equivalent of the language-babel package](https://github.com/michaelgmcd/vscode-language-babel).

**Comment by cjhowe7** [comment]
Another reason to support this is that prettier will format this: 

```js
`#graphql
export default `#graphql
  ...your graphql code here
`;
```

to this:

```js
export default `
  #graphql
  ...your graphql code here
`;
```

which will break highlighting. This makes it a non-option for prettier users. The comment form doesn't have this issue.

**Comment by kachkaev** [comment]
I just assembled a [PR](https://github.com/kumarharsh/graphql-for-vscode/pull/74) for this while on a meeting :–)

All worked locally, but feel free to check the new RegExp more rigorously!
