### ISSUE TITLE
js file highlighting broken when .gql is present anywhere in the file

### ISSUE THREAD

**Issue by yurigenin** [kumarharsh/graphql-for-vscode#7]
When you open a .js file and have a string that has '.gql' anywhere the highlighting is broken after that.

![image](https://cloud.githubusercontent.com/assets/11202960/20899643/7432a3ac-bae8-11e6-899b-9160eaa3e4c6.png)

**Comment by kumarharsh** [comment]
I'll.look into it. Thanks.

**Comment by kumarharsh** [comment]
Related issue: https://github.com/Microsoft/vscode/issues/2793
Related issue: https://github.com/Microsoft/vscode/issues/6858#issuecomment-221801714

I think it'll be "properly" fixed only when v8 ships with lookbehind support: http://v8project.blogspot.in/2016/02/regexp-lookbehind-assertions.html?m=1
https://github.com/Microsoft/vscode/issues/16891#issuecomment-265676639

**Comment by kumarharsh** [comment]
OK, after some digging, I found a few documents which highlight what all those textmate scopenames mean. Putting here for future documentation:

https://discuss.atom.io/t/grammar-injections/13412/3
https://github.com/textmate/markdown.tmbundle/issues/15

**Comment by julienp** [comment]
Thank you for the information, very useful!

**Comment by kumarharsh** [comment]
fixed in d021915eb42a117a3ed8770b3e0725aa723b49e5
