### ISSUE TITLE
Support GraphQL extends syntax

### ISSUE THREAD

**Issue by cjhowe7** [kumarharsh/graphql-for-vscode#72]
This is a syntax commonly used with Apollo. I believe all that is required for this is to add the `extend` keyword. I don't think this is officially part of GraphQL. This is how it looks now:

<img width="302" alt="screen shot 2018-02-13 at 5 37 45 pm" src="https://user-images.githubusercontent.com/29269679/36177727-a393198a-10e4-11e8-830e-fea598f8488f.png">

Ideally the `extend` keyword is highlighted.

In case it helps, [here's the commit that adds this feature to the Atom language-babel package](https://github.com/gandm/language-babel/commit/9f8fa420aa7dde89fa4f74ffe02f4516cec55047).

**Comment by kumarharsh** [comment]
Thanks for the issues, much appreciated. I'd work on these on the weekend (_hopefully_). Would be great if you can send a PR if you want the support sooner.
