### ISSUE TITLE
Support for introspected schemas?

### ISSUE THREAD

**Issue by bmayen** [kumarharsh/graphql-for-vscode#73]
Would like to use this for autocompletion of queries and fragments in our frontend repo, but as far as I can tell, that's not possible unless the backend code is colocated. Am I understanding this correctly?

We're using apollo-codegen to introspect a schema from another repo. Is there any way to use codegen's output `schema.json` here instead of requiring direct access to schema files in a separate repo?

**Comment by Mayank1791989** [comment]
> but as far as I can tell, that's not possible unless the backend code is colocated. Am I understanding this correctly?

No colocation is not required you can use printed schema.

> Is there any way to use codegen's output schema.json

Instead of generating ```schema.json``` generate ```schema.graphql``` and in .gqlconfig use path of generated file. If you are using apollo-codegen then use print-schema option to generate schema.graphql file.

**Comment by bmayen** [comment]
Ah, thanks for the feedback. This works perfectly.
