### ISSUE TITLE
Syntax Error: Unexpected $ for interpolated fragments.

### ISSUE THREAD

**Issue by FredyC** [kumarharsh/graphql-for-vscode#77]
Honestly, I am not sure if the issue is with the extension or upstream, but looking at this [piece of code](https://github.com/Mayank1791989/gql/blob/master/src/query/_shared/Parsers/QueryParser.js#L67) in `@playlyfe/gql` it feels like it should be handled there properly. However, looking at [graphql.json here](https://github.com/kumarharsh/graphql-for-vscode/blob/master/syntaxes/graphql.json#L664) it seems to be handled as well 🤔 

```ts
import { buildQuery } from '@graph/buildQuery'
import { Address } from '@graph/fragments'
import { GOrderList } from '@typings/types'
import gql from 'graphql-tag'

export const OrderListQuery = buildQuery<GOrderList.Query>(gql`
  ${Address} // <--- Syntax Error: Unexpected $
  query GOrderList {
    orders {
      id
      address {
        ...Address
      }
    }
  }
`)
```

I would add that the code is working just fine, everything compiles and runs. It's just an issue within the the VSCode.

**.gqlconfig**
```json5
{
  "schema": {
    "files": ["schema/schema.graphql"]
  },
  "query": {
    "files": [
      {
        "match": "src/**/*Query.ts",
        "parser": ["EmbeddedQueryParser", { "startTag": "gql`", "endTag": "`" }]
      }
    ]
  }
}
```

**Extension output**
```
[Info  - 19:10:27] NODE_PATH value is: d:\workspace\app
[Info  - 19:10:35] Module '@playlyfe/gql' loaded from: d:\workspace\app\node_modules\@playlyfe\gql\lib\index.js
[Watch established (gqlSchemaFiles)] 
	basePath: D:/workspace/app 
	RelativePath: undefined 
	Files: [
  "schema/schema.graphql"
]
[Watch established (gqlQueryFiles-0)] 
	basePath: D:/workspace/app 
	RelativePath: undefined 
	Files: "src/**/*Query.ts"
[vscode] File extensions registered:  [ 'graphql', 'ts' ]
```

**`@playlyfe/gql` v2.5.0**
Windows 10 x64

**Comment by Mayank1791989** [comment]
use v2.6.0

**Comment by FredyC** [comment]
Duh! I could have tried that for sure seeing the interpolation is actually in the code :) You are absolutely right. Well, at least if someone else stumbles upon this issue, they will know the cure :) Thanks!
