### ISSUE TITLE
wrong comment highlight

### ISSUE THREAD

**Issue by miaulightouch** [kumarharsh/graphql-for-vscode#82]
![default](https://user-images.githubusercontent.com/5199594/38133737-111d7500-3443-11e8-8bcf-8b9f1bdb9b35.PNG)

Expected:
triple quote should comment out all text that included.

Problem:
but it's not.

**Comment by kumarharsh** [comment]
You can use single quotes for single-line descriptions and triple quotes for multi-line ones.

**Comment by miaulightouch** [comment]
it's fetched from endpoint, maybe I may not have permission to ask them to use single quotes.

**Comment by brentron9000** [comment]
It seems triple quotes are the new standard for descriptions in ^graphql@0.12

[See here.](https://github.com/graphql-cli/graphql-cli/issues/182)
