### ISSUE TITLE
Add support for template literal highlighting in .vue files

### ISSUE THREAD

**Issue by flakeparadigm** [kumarharsh/graphql-for-vscode#84]
I'm wanting to work with GraphQL in Vue single-file components, however the file extensions list for the template literal syntax does not include `.vue` files, only JavaScript and TypeScript files. Would you consider adding support for the Vue files as well?

**Comment by flakeparadigm** [comment]
Sorry, after some experimentation and further exploration it turns out this appears to be an issue with VS Code and not this extension.

**Comment by kumarharsh** [comment]
I'll have a look at your closed PR this weekend. Thanks for taking the time for the PR. You didn't modify the package.json file though - maybe that's why its not working?

**Comment by flakeparadigm** [comment]
I should have added a reference to the issue that's causing this. Vetur actually designates the code block as JS (or TS) so in theory it should be automatic without having to change this extension.

https://github.com/vuejs/vetur/issues/701

**Comment by flakeparadigm** [comment]
I hadn't looked at the `package.json`, though, and found that adding the `vue` type there makes it work! I'll go ahead and open the updated PR.
