### ISSUE TITLE
Allow for different tag names

### ISSUE THREAD

**Issue by bradzacher** [kumarharsh/graphql-for-vscode#90]
The extension only colours graphql strings when they are template tagged with `gql`.

The `eslint-plugin-graphql` library lets you specify other tag types to work with different schemas.
For example, we have a schema for app A's API, and a schema for app B's API.

When writing queries, we can differentiate between them by renaming the `graphql-tag` import:
```
import gqlA from 'graphql-tag'

const query = gqlA`....`
```

It'd be good if you added a configuration option to add other template tag function names, so that we can have syntax highlighting that works with the eslint plugin.

**Comment by kumarharsh** [comment]
@bradzacher I don't think this will be possible. Syntax grammars are defined as static JSON files, and as far as I know, overriding them at run-time is not allowed by editors such as VSCode.

You can get syntax highlighting by writing the code as described here: https://github.com/kumarharsh/graphql-for-vscode/issues/69

**Comment by kumarharsh** [comment]
Please note that validation, etc will still work well, only for syntax highlighting would you need to use the `#graphql` or `/* GraphQL */` inline comment style.

**Comment by bradzacher** [comment]
I've started using the `/* GraphQL */` comment and it works fine.
