### ISSUE TITLE
Introspection file support

### ISSUE THREAD

**Issue by janbaykara** [kumarharsh/graphql-for-vscode#99]
It'd be groovy if this optionally took a { schema: { file: 'schema.json' } } introspection file.

**Comment by cgatian** [comment]
Looks like [this extension](https://marketplace.visualstudio.com/items?itemName=stpn.vscode-graphql) does the job

**Comment by janbaykara** [comment]
Yeah, I couldn't get that to work...

**Comment by pie6k** [comment]
Is there any update about it? I'd like to keep with this extention.

**Comment by Mayank1791989** [comment]
see issue https://github.com/Mayank1791989/gql/issues/65
